services:
  - type: web
    name: digitalhut
    runtime: node
    repo: https://github.com/tehleader1/Digitalhut
    branch: main
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
