create table if not exists digitalhut_users (
  wallet text primary key,
  tier text not null default 'free',
  downloads integer not null default 3,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists digitalhut_customers (
  wallet text primary key,
  email text,
  sms_phone text,
  sms_market_updates boolean not null default false,
  sms_observatory_updates boolean not null default false,
  home_address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists digitalhut_subscriptions (
  id bigint generated by default as identity primary key,
  wallet text,
  tier text not null,
  currency text not null default 'USD',
  amount numeric not null default 0,
  status text not null default 'payment-provider-needed',
  provider text not null default 'manual-intent',
  created_at timestamptz not null default now()
);

create table if not exists digitalhut_history (
  id bigint generated by default as identity primary key,
  wallet text,
  tier text,
  query text,
  target text,
  event_type text default 'observatory-event',
  result jsonb,
  created_at timestamptz not null default now()
);

create table if not exists digitalhut_downloads (
  id bigint generated by default as identity primary key,
  wallet text,
  tier text,
  asset text,
  model_uid text,
  provider text,
  allowed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists digitalhut_live_edits (
  id bigint generated by default as identity primary key,
  agent text,
  change_summary text not null,
  files jsonb default '[]'::jsonb,
  status text not null default 'applied',
  created_at timestamptz not null default now()
);

create table if not exists digitalhut_render_jobs (
  id bigint generated by default as identity primary key,
  wallet text,
  source_model text,
  scene_name text,
  render_status text not null default 'queued',
  output_path text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
